name: Build dev backend
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build dev backend and commit to 'dist/dev' branch
    runs-on: ubuntu-latest
    steps:
    - name: git checkout dev
      uses: actions/checkout@v3
      with:
        ref: dev
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Install and build
      run: cd backend; yarn install; yarn build;
    - name: Copy necessary files for deployment
      run: |
        cd backend
        cp ./package.json dist/package.json
        cp ./yarn.lock dist/yarn.lock
        cp -r ./scripts dist/scripts
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist-dev # The branch name where you want to push the assets
        FOLDER: backend/dist # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message